# 匯入模組與函示庫

In [1]:
from pytrends.request import TrendReq
from bs4 import BeautifulSoup
from selenium import webdriver
from sklearn import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import time
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pickle
import joblib
from xgboost import XGBClassifier
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [2]:
filename = "gbc_model.sav"

# 時間: 2020/01 ~ 2020/03

In [2]:
Jan_March = pd.read_csv("0429_google.csv")

In [3]:
Jan_March  = Jan_March[:-1]

In [5]:
Jan_March.tail()

,Date,momo,switch,蝦皮,pchome,衛生紙,口罩,星巴克,家樂福,樂天,...,計時器,計時器 廚房,記帳城市,記憶 桌遊,記憶卡512,袖釦,袖珍衛生紙,車用藍芽 fm,蝦皮商場,蝸牛霜高含量20%活膚原液50ml
67,2020-03-27,55.0,58.0,71.0,46.0,14.0,27.0,3.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,2020-03-28,61.0,77.0,67.0,43.0,15.0,33.0,3.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,2020-03-29,62.0,91.0,60.0,41.0,14.0,24.0,3.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,2020-03-30,56.0,71.0,74.0,48.0,12.0,34.0,5.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,2020-03-31,64.0,70.0,81.0,45.0,10.0,26.0,6.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_april = pd.read_csv("april_googleTrend.csv")

In [6]:
columns = df_april.columns

In [7]:
len(columns)

7781

In [8]:
df_1_3 = df_1_3[columns]

In [9]:
df_1_3.shape

(72, 7781)

In [10]:
df_1_3.tail()

,Date,momo,switch,蝦皮,pchome,衛生紙,口罩,星巴克,家樂福,樂天,...,調光簾,LG V40 ThinQ,小背包,3m s004,小腿,貓零食,小米有品德爾瑪,kiehl's契爾氏,keyway,魔術道具
67,2020-03-27,55.0,58.0,71.0,46.0,14.0,27.0,3.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,2020-03-28,61.0,77.0,67.0,43.0,15.0,33.0,3.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,2020-03-29,62.0,91.0,60.0,41.0,14.0,24.0,3.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,2020-03-30,56.0,71.0,74.0,48.0,12.0,34.0,5.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,2020-03-31,64.0,70.0,81.0,45.0,10.0,26.0,6.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = pd.concat([df_1_3,df_april])

In [12]:
df.index = np.arange(1,len(df)+1)

# 2020/01 ~ 2020/04 
# All data

In [13]:
df.tail()

,Date,momo,switch,蝦皮,pchome,衛生紙,口罩,星巴克,家樂福,樂天,...,調光簾,LG V40 ThinQ,小背包,3m s004,小腿,貓零食,小米有品德爾瑪,kiehl's契爾氏,keyway,魔術道具
98,2020-04-26,66.0,71.0,63.0,43.0,7.0,16.0,3.0,6.0,1.0,...,16.0,0.0,16.0,0.0,40.0,0.0,0.0,50.0,67.0,0.0
99,2020-04-27,72.0,70.0,75.0,45.0,6.0,23.0,5.0,4.0,1.0,...,0.0,0.0,12.0,5.0,40.0,31.0,0.0,0.0,63.0,0.0
100,2020-04-28,71.0,58.0,83.0,68.0,7.0,22.0,4.0,4.0,1.0,...,5.0,0.0,8.0,0.0,75.0,0.0,0.0,31.0,31.0,0.0
101,2020-04-29,67.0,60.0,92.0,46.0,8.0,21.0,4.0,5.0,2.0,...,10.0,0.0,8.0,0.0,48.0,31.0,0.0,0.0,31.0,0.0
102,2020-04-30,62.0,56.0,82.0,64.0,6.0,20.0,3.0,4.0,1.0,...,0.0,0.0,4.0,0.0,35.0,0.0,0.0,55.0,0.0,0.0

# Define functions

In [14]:
def google_api(data_feed):
    df = pd.DataFrame()
    pytrend = TrendReq(hl='en-US',tz=360 )
    #pytrends = TrendReq(hl='en-US', tz=360, timeout=(10,25), proxies=['https://34.203.233.13:80'], retries=5, backoff_factor=0.1)
    for i in tqdm(range(5,len(data_feed),5)):
        time.sleep(1.5)
        kw = data_feed[i-5:i]
        pytrend.build_payload(kw_list=kw,cat=0,timeframe='2020-01-01 2020-04-01',geo='TW',gprop='')
        data = pytrend.interest_over_time()
        df = pd.concat([df,data],axis=1,sort=False)
        
    df.drop(['isPartial'],axis=1,inplace=True)
    return df

In [15]:
def xgb(x,y):
    model = XGBClassifier()
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    predictions = [round(value) for value in y_pred]
    accuracy = accuracy_score(y_test, predictions)
    print("Accuracy: %.2f%%" % (accuracy * 100.0))

In [16]:
def gbc(x,y):
    state = 12  
    test_size = 0.2 
  
    X_train, X_val, y_train, y_val = train_test_split(x, y, test_size=test_size, random_state=state)
    lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]
    for learning_rate in lr_list:
        gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=2, max_depth=2, random_state=0)
        gb_clf.fit(X_train, y_train)
        print("Learning rate: ", learning_rate)
        print("Accuracy score (training): {0:.3f}".format(gb_clf.score(X_train, y_train)))
        print("Accuracy score (validation): {0:.3f}".format(gb_clf.score(X_val, y_val)))
    
    #filename = "gbc_model.sav"
    #pickle.dump(gb_clf,open(filename,'wb'))
    joblib.dump(gb_clf,filename)

In [17]:
def call_gbc():
    filename = "gbc_model_1.sav"
    load_model = pickle.load(open(filename,'wb'))
    return load_model

In [18]:
def linear_model(x,y):
    X_train, X_test, y_train, y_test = train_test_split(x[['past_Q_average','Trend_now']], y['result'], test_size=0.33, random_state=42)
    lr = LinearRegression()
    lr.fit(X_train,y_train)
    y_pred = lr.predict(X_test)
    print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
    print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
    print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
    
    return y_pred

In [19]:
def feature_engineering(df):
    
    print(df.isnull().sum())
    print(df.shape)
    df.reset_index(level=0,inplace=True)
    df.rename(columns={'date':'Date'},inplace=True)
    df.index = np.arange(1,len(df)+1)
    df['Date'] = df['Date'].astype(str).apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d').date()) 
    df['Year'] = df['Date'].apply(lambda x: datetime.datetime.strftime(x, '%Y')).astype('int64')
    df['Month'] = df['Date'].apply(lambda x: datetime.datetime.strftime(x, '%m')).astype('int64')
    df['Day'] = df['Date'].apply(lambda x: datetime.datetime.strftime(x, '%d')).astype('int64')
    
    return df

In [20]:
def train_dataframe(df):

    x = df[:66] 
    x.drop(['Date'],axis=1,inplace=True)
    feature = {'Word':[],'past_Q_average':[],'Trend_now':[]}
    prediction_y = []
    columns = x.columns
    for c in columns:
        feature['Word'].append(c)
        feature['past_Q_average'].append(sum(x[c])/len(x))   
    
    trend_now = df[42:66]
    trend_now.drop(['Date'],axis=1,inplace=True)  
    for c in columns:
        num = 0
        for d in trend_now[c]:
            num+=d
        feature['Trend_now'].append(num/len(trend_now))
    feature = pd.DataFrame(feature)
    
    '''
        Setting Prediction -Y 
        this week average trend degree 
    '''
    target_prediction = df[66:]
    target_prediction.drop(['Date'],axis=1,inplace=True)
    for c in columns:
        num = 0
        for d in target_prediction[c]:
            num+=d
        prediction_y.append(num/len(target_prediction))
    #target_prediction = target_prediction.T
    #print(target_prediction)
    y = pd.DataFrame(prediction_y)
    
    
    
    classification = []
    for i,j in zip(prediction_y,feature['Trend_now']):
        if i-j>0:
            
            classification.append(1)
        else:
            classification.append(0)
            
    y['result'] = classification  
    
     
    return feature,y

# 透過訓練 1~4  月份資料預測 5/1 趨勢

In [21]:
df.dropna(axis=1,inplace=True)

In [22]:
df.shape

(102, 5841)

# Data Cleaning

In [23]:
df.isnull().sum()

Date      0
momo      0
switch    0
蝦皮        0
pchome    0
         ..
雷達電蚊香     0
byw       0
電信        0
電力式保溫鍋    0
打卡機       0
Length: 5841, dtype: int64

In [24]:
df_train = df

In [25]:
df_train = df.drop(['Date'],axis=1)

In [26]:
words = df_train.columns

In [27]:
feature = {'Word':[],'past_Q_average':[],'Past_1_month':[],'Past_week':[]}
for c in words:
    feature['Word'].append(c)
    feature['past_Q_average'].append(sum(df_train[c])/len(df_train))

In [28]:
df[72:]

,Date,momo,switch,蝦皮,pchome,衛生紙,口罩,星巴克,家樂福,樂天,...,打呼,雪黛屋,我的心機 濃潤玻尿酸,我的視角,打印機,雷達電蚊香,byw,電信,電力式保溫鍋,打卡機
73,2020-04-01,62.0,86.0,76.0,44.0,11.0,60.0,4.0,4.0,1.0,...,58.0,0.0,0.0,0.0,23.0,0.0,0.0,96.0,0.0,1.0
74,2020-04-02,62.0,100.0,66.0,44.0,9.0,52.0,4.0,5.0,1.0,...,71.0,0.0,0.0,0.0,24.0,0.0,0.0,86.0,0.0,0.0
75,2020-04-03,67.0,83.0,74.0,40.0,9.0,49.0,4.0,5.0,1.0,...,49.0,0.0,0.0,0.0,0.0,1.0,1.0,77.0,0.0,0.0
76,2020-04-04,68.0,91.0,68.0,47.0,12.0,54.0,4.0,6.0,1.0,...,100.0,0.0,0.0,0.0,25.0,1.0,0.0,72.0,0.0,0.0
77,2020-04-05,64.0,88.0,73.0,48.0,13.0,44.0,4.0,4.0,1.0,...,98.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0
78,2020-04-06,63.0,83.0,76.0,56.0,13.0,50.0,3.0,5.0,2.0,...,67.0,0.0,0.0,0.0,0.0,1.0,0.0,94.0,0.0,1.0
79,2020-04-07,75.0,74.0,81.0,54.0,10.0,44.0,5.0,4.0,2.0,...,69.0,0.0,0.0,0.0,46.0,1.0,0.0,91.0,0.0,0.0
80,2020-04-08,78.0,82.0,84.0,50.0,12.0,62.0,4.0,4.0,2.0,...,45.0,0.0,0.0,0.0,23.0,1.0,0.0,79.0,0.0,1.0
81,2020-04-09,78.0,90.0,95.0,49.0,13.0,100.0,4.0,4.0,2.0,...,33.0,0.0,0.0,0.0,0.0,1.0,0.0,82.0,0.0,0.0
82,2020-04-10,72.0,77.0,80.0,48.0,10.0,68.0,4.0,5.0,2.0,...,68.0,0.0,0.0,0.0,68.0,1.0,0.0,89.0,0.0,0.0
83,2020-04-11,65.0,85.0,63.0,45.0,9.0,69.0,3.0,5.0,1.0,...,35.0,0.0,0.0,0.0,24.0,1.0,0.0,72.0,0.0,0.0
84,2020-04-12,64.0,84.0,66.0,44.0,9.0,53.0,4.0,6.0,2.0,...,99.0,0.0,0.0,0.0,25.0,0.0,0.0,54.0,0.0,0.0
85,2020-04-13,62.0,68.0,85.0,49.0,11.0,61.0,5.0,5.0,2.0,...,58.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,0.0,0.0
86,2020-04-14,63.0,67.0,89.0,52.0,7.0,66.0,5.0,4.0,2.0,...,34.0,0.0,0.0,0.0,0.0,0.0,0.0,85.0,0.0,1.0
87,2020-04-15,74.0,70.0,72.0,48.0,8.0,75.0,4.0,4.0,2.0,...,34.0,0.0,0.0,0.0,23.0,0.0,0.0,88.0,0.0,1.0
88,2020-04-16,60.0,70.0,86.0,55.0,8.0,53.0,4.0,6.0,2.0,...,44.0,0.0,0.0,0.0,0.0,1.0,0.0,97.0,0.0,0.0
89,2020-04-17,64.0,70.0,74.0,48.0,6.0,44.0,3.0,6.0,2.0,...,34.0,0.0,0.0,0.0,22.0,1.0,0.0,100.0,0.0,0.0
90,2020-04-18,61.0,74.0,72.0,41.0,5.0,38.0,3.0,6.0,2.0,...,24.0,0.0,0.0,0.0,24.0,0.0,0.0,76.0,0.0,0.0
91,2020-04-19,64.0,74.0,62.0,45.0,8.0,24.0,3.0,16.0,2.0,...,73.0,0.0,0.0,0.0,0.0,0.0,0.0,79.0,0.0,0.0
92,2020-04-20,65.0,59.0,83.0,45.0,5.0,27.0,3.0,19.0,2.0,...,55.0,0.0,0.0,0.0,44.0,0.0,0.0,88.0,0.0,0.0
93,2020-04-21,65.0,64.0,86.0,52.0,8.0,28.0,3.0,7.0,1.0,...,33.0,0.0,0.0,0.0,0.0,1.0,0.0,96.0,0.0,0.0
94,2020-04-22,78.0,57.0,81.0,46.0,6.0,39.0,4.0,6.0,2.0,...,34.0,0.0,0.0,0.0,22.0,1.0,0.0,88.0,0.0,0.0
95,2020-04-23,68.0,61.0,76.0,53.0,9.0,36.0,4.0,5.0,2.0,...,33.0,0.0,0.0,0.0,22.0,0.0,0.0,95.0,0.0,0.0
96,2020-04-24,69.0,78.0,68.0,49.0,7.0,28.0,3.0,5.0,1.0,...,69.0,0.0,0.0,0.0,23.0,1.0,0.0,92.0,0.0,1.0
97,2020-04-25,69.0,72.0,68.0,43.0,8.0,23.0,3.0,6.0,1.0,...,24.0,0.0,0.0,0.0,0.0,1.0,0.0,85.0,0.0,1.0
98,2020-04-26,66.0,71.0,63.0,43.0,7.0,16.0,3.0,6.0,1.0,...,60.0,0.0,0.0,0.0,0.0,1.0,0.0,74.0,0.0,0.0
99,2020-04-27,72.0,70.0,75.0,45.0,6.0,23.0,5.0,4.0,1.0,...,79.0,0.0,0.0,0.0,23.0,1.0,0.0,92.0,0.0,0.0
100,2020-04-28,71.0,58.0,83.0,68.0,7.0,22.0,4.0,4.0,1.0,...,80.0,0.0,0.0,0.0,45.0,1.0,0.0,99.0,0.0,0.0
101,2020-04-29,67.0,60.0,92.0,46.0,8.0,21.0,4.0,5.0,2.0,...,57.0,0.0,0.0,0.0,0.0,0.0,0.0,73.0,0.0,0.0
102,2020-04-30,62.0,56.0,82.0,64.0,6.0,20.0,3.0,4.0,1.0,...,40.0,0.0,0.0,0.0,20.0,2.0,0.0,98.0,0.0,0.0

In [29]:
past_1month = df_train[72:]
for c in words:
    num = 0
    feature['Past_1_month'].append(sum(past_1month[c])/len(past_1month))

In [30]:
past_week = df_train[95:]
for c in words:
    num = 0
    feature['Past_week'].append(sum(past_week[c])/len(past_week))

In [31]:
data_feed = pd.read_csv("shopslist.csv")

In [32]:
data_feed.head()

     內容標籤  事件總數
0    momo  5152
1  switch  2495
2      蝦皮  2377
3  pchome  2004
4     衛生紙  1653

In [33]:
total_event = data_feed.loc[data_feed['內容標籤'].isin(words)]

In [34]:
len(total_event)

5840

In [35]:
te = []
for i in total_event['事件總數']:
    te.append(i)

In [36]:
feature = pd.DataFrame(feature)

In [37]:
feature['total_events'] = te

In [38]:
feature.head()

     Word  past_Q_average  Past_1_month  Past_week  total_events
0    momo       68.254902     67.266667  68.000000          5152
1  switch       53.107843     74.066667  66.428571          2495
2      蝦皮       70.166667     76.633333  75.857143          2377
3  pchome       49.676471     48.700000  51.142857          2004
4     衛生紙       13.088235      8.666667   7.000000          1653

# 將字詞轉換成Label Encoding

In [39]:
feature['word_le'] = le.fit_transform(feature['Word'])

# 過濾 廠商字詞

In [40]:
all_shop = []
shop = pd.read_csv("shop_list.csv")
for s in shop['list']:
    all_shop.append(s)

In [41]:
feature = feature[feature['Word'].map(lambda x:x not in all_shop)]

In [42]:
feature.index = np.arange(1,len(feature)+1)

In [43]:
target_words = []
for w in feature['Word']:
    target_words.append(w)

In [44]:
target = pd.DataFrame()
target['word'] = target_words
target.to_csv("target.csv",index=False)

In [45]:
x = feature.drop(['Word'],axis=1)

In [46]:
df.tail()

,Date,momo,switch,蝦皮,pchome,衛生紙,口罩,星巴克,家樂福,樂天,...,打呼,雪黛屋,我的心機 濃潤玻尿酸,我的視角,打印機,雷達電蚊香,byw,電信,電力式保溫鍋,打卡機
98,2020-04-26,66.0,71.0,63.0,43.0,7.0,16.0,3.0,6.0,1.0,...,60.0,0.0,0.0,0.0,0.0,1.0,0.0,74.0,0.0,0.0
99,2020-04-27,72.0,70.0,75.0,45.0,6.0,23.0,5.0,4.0,1.0,...,79.0,0.0,0.0,0.0,23.0,1.0,0.0,92.0,0.0,0.0
100,2020-04-28,71.0,58.0,83.0,68.0,7.0,22.0,4.0,4.0,1.0,...,80.0,0.0,0.0,0.0,45.0,1.0,0.0,99.0,0.0,0.0
101,2020-04-29,67.0,60.0,92.0,46.0,8.0,21.0,4.0,5.0,2.0,...,57.0,0.0,0.0,0.0,0.0,0.0,0.0,73.0,0.0,0.0
102,2020-04-30,62.0,56.0,82.0,64.0,6.0,20.0,3.0,4.0,1.0,...,40.0,0.0,0.0,0.0,20.0,2.0,0.0,98.0,0.0,0.0

# 載入之前訓練過的模型進行新資料的訓練

In [47]:
model = joblib.load(filename)

In [48]:
y = df[101:]

In [49]:
y = y.drop(['Date'],axis=1)

In [50]:
y = y[target_words]

In [51]:
y = y.T

In [52]:
y = y.rename(columns={102:'result'})

In [53]:
y['Word'] = target_words

In [54]:
y.index = np.arange(1,len(y)+1)

In [55]:
len(y)

5817

In [56]:
len(x)

5817

In [57]:
classification = []
for i,j in zip(y['result'],x['Past_week']):
    if i-j>0:
        classification.append(1)
    else:
        classification.append(0)
            
y['real case'] = classification

In [58]:
feature.columns

Index(['Word', 'past_Q_average', 'Past_1_month', 'Past_week', 'total_events',
       'word_le'],
      dtype='object')

# XGBoosting 訓練準確率為 77.06%

In [59]:
xgb(feature[['past_Q_average','Past_1_month','Past_week','total_events']],y['real case'])

Accuracy: 78.18%

# Gradient Boosting Classifier

In [60]:
gbc(feature[['past_Q_average','Past_1_month','Past_week','total_events']],y['real case'])

Learning rate:  0.05
Accuracy score (training): 0.769
Accuracy score (validation): 0.773
Learning rate:  0.075
Accuracy score (training): 0.769
Accuracy score (validation): 0.773
Learning rate:  0.1
Accuracy score (training): 0.769
Accuracy score (validation): 0.773
Learning rate:  0.25
Accuracy score (training): 0.772
Accuracy score (validation): 0.772
Learning rate:  0.5
Accuracy score (training): 0.780
Accuracy score (validation): 0.771
Learning rate:  0.75
Accuracy score (training): 0.783
Accuracy score (validation): 0.769
Learning rate:  1
Accuracy score (training): 0.790
Accuracy score (validation): 0.750

In [61]:
predict_y = pd.read_csv("prediction4000.csv")

In [62]:
top_4000 = []
top_4000 = predict_y.columns
predict_y.head()

,switch,衛生紙,口罩,星巴克,家樂福,樂天,屈臣氏,小米,酒精,博客來,...,海鴻豬腳,米奇鞋子,充電電踞,充電頭 divi,男 真皮 涼鞋,夢娜麗莎洗髮精,夢素肌,wemo,米家 掃拖機器人,米家 洗手
0,100,4,93,27,33,25,29,100,23,44,...,100,0,0,0,0,0,0,100,33,0

In [63]:
predict_y.T

            0
switch    100
衛生紙         4
口罩         93
星巴克        27
家樂福        33
...       ...
夢娜麗莎洗髮精     0
夢素肌         0
wemo      100
米家 掃拖機器人   33
米家 洗手       0

[3745 rows x 1 columns]

In [64]:
predict_y = predict_y.T

In [65]:
trend_result = []
for i in predict_y[0]:
    trend_result.append(i)

In [66]:
y_test = pd.DataFrame()
y_test['Word'] = top_4000
y_test['Trend Result'] = trend_result

In [67]:
len(y_test)

3745

In [68]:
feature = feature.loc[feature.Word.isin(top_4000)]

In [69]:
feature.index = np.arange(1,len(feature)+1)

In [96]:
y_test.isnull().sum()

Word            0
Trend Result    0
真實漲跌            0
模型預測            0
漲跌機率            0
Result          0
dtype: int64

In [70]:
classification = []
for i,j in zip(y_test['Trend Result'],feature['Past_week']):
    if i-j>0:
        classification.append(1)
    else:
        classification.append(0)
            
y_test['真實漲跌'] = classification

In [71]:
y_prediction_pro = model.predict_proba(feature[['past_Q_average','Past_1_month','Past_week','total_events']])[:,1]  
y_prediction= model.predict(feature[['past_Q_average','Past_1_month','Past_week','total_events']])

# GBC 預測5/1 僅有 56.23%

In [72]:
accuracy = accuracy_score(y_test['真實漲跌'], y_prediction)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 56.23%

In [73]:
y_test['模型預測'] = y_prediction
y_test['漲跌機率'] = y_prediction_pro

In [74]:
y_test

          Word  Trend Result  真實漲跌  模型預測      漲跌機率
0       switch           100     1     0  0.043216
1          衛生紙             4     0     0  0.100441
2           口罩            93     1     0  0.046637
3          星巴克            27     1     0  0.143803
4          家樂福            33     1     0  0.100441
...        ...           ...   ...   ...       ...
3740   夢娜麗莎洗髮精             0     0     0  0.002502
3741       夢素肌             0     0     0  0.234147
3742      wemo           100     1     0  0.224746
3743  米家 掃拖機器人            33     1     0  0.151592
3744     米家 洗手             0     0     0  0.006463

[3745 rows x 5 columns]

In [75]:
feature

          Word  past_Q_average  Past_1_month  Past_week  total_events  word_le
1       switch       53.107843     74.066667  66.428571          2495     1485
2          衛生紙       13.088235      8.666667   7.000000          1653     5164
3           口罩       35.617647     44.966667  21.857143          1583     2362
4          星巴克        3.421569      3.766667   3.571429          1323     3453
5          家樂福        4.441176      5.833333   4.857143          1206     2960
...        ...             ...           ...        ...           ...      ...
3741   夢娜麗莎洗髮精        0.000000      0.000000   0.000000             2     2671
3742       夢素肌        8.176471      6.500000  21.142857             2     2672
3743      wemo        0.980392      1.233333   1.000000             2     1685
3744  米家 掃拖機器人        0.098039      0.266667   0.000000             2     4555
3745     米家 洗手        0.009804      0.000000   0.000000             2     4556

[3745 rows x 6 columns]

In [76]:
y_test.sort_values(by=['漲跌機率'],ascending=False)

        Word  Trend Result  真實漲跌  模型預測      漲跌機率
718        蝦           100     1     1  0.990366
2403   Coach           100     1     1  0.985656
2573     保護貼           100     1     1  0.985656
3536      舒壓           100     1     1  0.984175
1838      洗衣           100     1     1  0.981287
...      ...           ...   ...   ...       ...
3059   厚底涼拖鞋             0     0     0  0.002502
3061     宜瑪氏             0     0     0  0.002502
3385    台梗9號             0     0     0  0.002502
3382    無線車充             0     0     0  0.002502
3297  北歐復刻餐椅             0     0     0  0.002502

[3745 rows x 5 columns]

In [77]:
y_test.index = np.arange(1,len(y_test)+1)

# Prediction Report

In [78]:
confusion_matrix(y_test['真實漲跌'], y_prediction)

array([[1838,   41],
       [1598,  268]])

In [79]:
print("Classification Report")
print(classification_report(y_test['真實漲跌'], y_prediction, labels=[0,1]))

Classification Report
              precision    recall  f1-score   support

           0       0.53      0.98      0.69      1879
           1       0.87      0.14      0.25      1866

    accuracy                           0.56      3745
   macro avg       0.70      0.56      0.47      3745
weighted avg       0.70      0.56      0.47      3745

In [81]:
result = []
for i,j in zip(y_test['真實漲跌'], y_prediction):
    if i!=j:
        result.append("false")
    else:
        result.append("true")
y_test['Result'] = result

# Explore mispredict elements

In [84]:
false_prediction = y_test[y_test.Result=="false"]

In [99]:
false_prediction.describe()

       Trend Result         真實漲跌         模型預測         漲跌機率
count   1639.000000  1639.000000  1639.000000  1639.000000
mean      56.909091     0.974985     0.025015     0.345900
std       38.546956     0.156219     0.156219     0.095613
min        0.000000     0.000000     0.000000     0.002502
25%       18.000000     1.000000     0.000000     0.293376
50%       54.000000     1.000000     0.000000     0.347232
75%      100.000000     1.000000     0.000000     0.409619
max      100.000000     1.000000     1.000000     0.932767

In [85]:
false_prediction.head()

     Word  Trend Result  真實漲跌  模型預測      漲跌機率 Result
1  switch           100     1     0  0.043216  false
3      口罩            93     1     0  0.046637  false
4     星巴克            27     1     0  0.143803  false
5     家樂福            33     1     0  0.100441  false
6      樂天            25     1     0  0.143803  false

In [100]:
false_prediction = false_prediction[false_prediction.真實漲跌==1]

In [101]:
false_predict_element = false_prediction['Word'].unique()

In [106]:
len(false_predict_element)

1598

In [102]:
false_x = feature[feature.Word.isin(false_predict_element)]

In [103]:
false_x.index = np.arange(1,len(false_x)+1)

In [104]:
real = []
for i in false_prediction['Trend Result']:
    real.append(i)
false_x['真實趨勢熱度'] =real

/Users/steven_tseng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [105]:
false_x.head(20)

,Word,past_Q_average,Past_1_month,Past_week,total_events,word_le,真實趨勢熱度
1,switch,53.107843,74.066667,66.428571,2495,1485,100
2,口罩,35.617647,44.966667,21.857143,1583,2362,93
3,星巴克,3.421569,3.766667,3.571429,1323,3453,27
4,家樂福,4.441176,5.833333,4.857143,1206,2960,33
5,樂天,1.382353,1.566667,1.142857,935,3608,25
6,屈臣氏,2.000000,2.166667,2.142857,892,3076,29
7,小米,17.205882,21.400000,17.714286,872,3016,100
8,酒精,18.284314,10.533333,6.428571,822,5372,23
9,博客來,8.696078,9.466667,9.000000,806,2303,44
10,咖啡,73.264706,75.966667,74.714286,671,2495,86
11,爭鮮,3.235294,3.500000,4.000000,518,4109,5
12,nike,66.588235,72.500000,67.000000,488,1129,100
13,大樹,24.431373,24.566667,23.142857,485,2701,29
14,康是美,21.068627,22.633333,20.285714,452,3162,33
15,lativ,25.617647,25.833333,26.285714,408,1023,36
16,氣炸鍋,58.068627,72.200000,71.428571,400,3666,100
17,倩碧,3.431373,5.066667,4.000000,382,2045,10
18,airpods,44.852941,42.900000,41.428571,374,499,79
19,ipad,20.901961,18.866667,18.714286,356,932,80
20,switch lite,3.156863,4.733333,3.428571,291,1487,4

# 上述皆為預測錯誤的資料
1. 主要集中在真實為上漲，模型預測下跌的資料

In [107]:
false_x = false_x.drop(['word_le'],axis=1)

In [109]:
false_x.to_csv("false_predict_1.csv",index=False)

# Test - 4000 品

In [111]:
df_ = pd.read_csv("top_items.csv")

In [112]:
df_.shape

(333522, 5)

In [115]:
df_.head(10)

,product name,L1,L2,L3,事件數
0,5 月・微景設計・摩艾多肉植物復活島,美食生鮮,飲料/沖泡品,茶葉茶包,13741
1,【Sorella欣姿芳】繽紛 美臀三角小褲 M.L.EL-粉 ES1783-PIK,流行服飾,女性內睡衣,女性內褲,7544
2,Samsung Galaxy M11 (3G/32G) 6.4吋 四鏡頭智慧手機,手機相機,手機/平板,Android平板,7393
3,深夜呢喃‧法式薄襯蕾絲無鋼圈包覆集中款(灰色) S~XL Choco Shop,流行服飾,女性內睡衣,女性內衣,4403
4,大尺碼Annabery魅黑透視網紗開衩裙襬二件式睡衣,流行服飾,女性內睡衣,女睡衣居家服,4198
5,NS Switch主機單機 電續加長版+健身環 + 精選遊戲x2 + 主機鋼化玻璃保護貼,電腦電玩,電玩主機及週邊,其他電玩主機,4173
6,White Nights>1/2網紗無襯>C-D罩杯>耀眼藍(4065)【Passionata】,流行服飾,女性內睡衣,女性內衣,4127
7,FISICO Swim briefs - Item 47258530,運動戶外,運動鞋/服飾/配件,泳裝比基尼,4064
8,睡衣 MyDoll 凱特摩登x蕾絲綁帶睡衣三件組(黑x藍x桃/3色/XS-2L適穿),流行服飾,女性內睡衣,女睡衣居家服,3993
9,台灣公司貨 SWITCH 主機 動物森友會 動物之森 現貨只有一台,電腦電玩,電玩主機及週邊,Switch週邊,3989